
export const COLLECTIONS = {
  USERS: 'users',
  COMPANIES: 'companies',
  DEPARTMENTS: 'departments',
  EMPLOYEES: 'employees',
  DOCUMENTS: 'documents',
  SETTINGS: 'settings',
  CONTACTS: 'contacts',
  
  CRM: {
    CLIENTS: 'crm_clients',
    PROSPECTS: 'crm_prospects',
    REMINDERS: 'crm_reminders',
    OPPORTUNITIES: 'crm_opportunities',
    LEADS: 'crm_leads',
    CONTACTS: 'crm_contacts',
    DEALS: 'crm_deals',
    SETTINGS: 'crm_settings',
  },
  
  ACCOUNTING: {
    INVOICES: 'accounting_invoices',
    PAYMENTS: 'accounting_payments',
    EXPENSES: 'accounting_expenses',
    CLIENTS: 'accounting_clients',
    SUPPLIERS: 'accounting_suppliers',
    REPORTS: 'accounting_reports',
    TAXES: 'accounting_taxes',
    SETTINGS: 'accounting_settings',
    TRANSACTIONS: 'accounting_transactions',
    PERMISSIONS: 'accounting_permissions',
  },
  
  FREIGHT: {
    SHIPMENTS: 'freight_shipments',
    CARRIERS: 'freight_carriers',
    CONTAINERS: 'freight_containers',
    PACKAGES: 'freight_packages',
    TRACKING: 'freight_tracking',
    TRACKING_EVENTS: 'freight_tracking_events',
    ROUTES: 'freight_routes',
    PACKAGE_TYPES: 'freight_package_types',
    DOCUMENTS: 'freight_documents',
    PRICING: 'freight_pricing',
    QUOTES: 'freight_quotes',
    CUSTOMERS: 'freight_customers',
    BILLING: 'freight_billing',
    SETTINGS: 'freight_settings',
    DRIVERS: 'freight_drivers',
    VEHICLES: 'freight_vehicles'
  },
  
  HR: {
    EMPLOYEES: 'hr-employees',
    LEAVES: 'hr-leaves',
    CONTRACTS: 'hr-contracts',
    POSITIONS: 'hr-positions',
    DEPARTMENTS: 'hr-departments',
    EVALUATIONS: 'hr-evaluations',
    PAYSLIPS: 'hr-payslips',
    RECRUITMENT: 'hr-recruitment',
    TRAININGS: 'hr-trainings',
    BADGES: 'hr-badges',
    ATTENDANCE: 'hr-attendance',
    ABSENCE_REQUESTS: 'hr-absence_requests',
    DOCUMENTS: 'hr-documents',
    TIMESHEETS: 'hr-timesheets',
    REPORTS: 'hr-reports',
    ALERTS: 'hr-alerts',
    LEAVE_REQUESTS: 'hr-leave_requests',
    ABSENCES: 'hr-absences',
    SALARIES: 'hr-salaries',
  },
  
  HEALTH: {
    PATIENTS: 'health-patients',
    DOCTORS: 'health-doctors',
    APPOINTMENTS: 'health-appointments',
    CONSULTATIONS: 'health-consultations',
    MEDICAL_RECORDS: 'health-medical_records',
    PRESCRIPTIONS: 'health-prescriptions',
    INSURANCE: 'health-insurance',
    BILLING: 'health-billing',
    SETTINGS: 'health-settings',
    HEALTH_CONSULTATIONS: 'health-consultations',
    HEALTH_INSURANCE: 'health-insurance',
    HEALTH_BILLING: 'health-billing',
    STAFF: 'health-staff',
  },
  
  USER_PERMISSIONS: 'userPermissions',
};
