
import { Supplier } from '../types/garage-types';

export const suppliers: Supplier[] = [
  {
    id: 'SUP001',
    name: 'Auto Pièces Express',
    email: 'contact@autopiecesexpress.fr',
    phone: '01 23 45 67 89',
    address: '123 Rue de la Mécanique, 75001 Paris',
    category: 'parts',
    specialties: ['Freins', 'Suspension', 'Filtration'],
    rating: 4.5,
    activeContracts: 3,
    status: 'active',
    lastOrderDate: '2025-04-15',
    paymentTerms: 'Net 30',
    notes: 'Fournisseur principal pour les pièces de freinage',
  },
  {
    id: 'SUP002',
    name: 'Outils Pro Auto',
    email: 'ventes@outilsproauto.fr',
    phone: '01 98 76 54 32',
    address: '456 Avenue des Outils, 69001 Lyon',
    category: 'tools',
    specialties: ['Outillage spécialisé', 'Diagnostic', 'Équipement atelier'],
    rating: 4.8,
    activeContracts: 2,
    status: 'active',
    lastOrderDate: '2025-04-10',
    paymentTerms: 'Net 45',
    notes: 'Excellente qualité d\'outils pour l\'atelier',
  },
  {
    id: 'SUP003',
    name: 'Accessoires Auto Deluxe',
    email: 'info@accessoiresautodeluxe.fr',
    phone: '03 45 67 89 10',
    address: '789 Boulevard des Accessoires, 33000 Bordeaux',
    category: 'accessories',
    specialties: ['Intérieur', 'Extérieur', 'Électronique'],
    rating: 4.2,
    activeContracts: 1,
    status: 'active',
    lastOrderDate: '2025-04-05',
    paymentTerms: 'Net 15',
    notes: 'Bon rapport qualité-prix pour les accessoires',
  },
  {
    id: 'SUP004',
    name: 'Pneus Premier Choix',
    email: 'contact@pneuspc.fr',
    phone: '04 56 78 91 23',
    address: '321 Rue du Caoutchouc, 59000 Lille',
    category: 'parts',
    specialties: ['Pneus été', 'Pneus hiver', 'Jantes'],
    rating: 4.6,
    activeContracts: 2,
    status: 'inactive',
    lastOrderDate: '2025-03-25',
    paymentTerms: 'Net 30',
    notes: 'Actuellement en rupture de stock sur plusieurs références',
  },
];
