import {
  DriverAvailabilityPeriod,
  MapExtensionRequest,
  TransportDriver,
  TransportVehicle,
  TransportVehicleLocation,
} from '../types';

export const mockDrivers: TransportDriver[] = [
  {
    id: 'driver-1',
    firstName: 'Jean',
    lastName: 'Dupont',
    email: 'jean.dupont@example.com',
    phone: '+33612345678',
    address: '123 Rue de la Paix, 75001 Paris',
    licenseNumber: '1234567890',
    availability: 'Available',
    vehicleId: 'vehicle-1',
    notes: [],
    schedule: [],
    rating: 4.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'driver-2',
    firstName: 'Marie',
    lastName: 'Martin',
    email: 'marie.martin@example.com',
    phone: '+33698765432',
    address: '456 Avenue des Champs-Élysées, 75008 Paris',
    licenseNumber: '0987654321',
    availability: 'Busy',
    vehicleId: 'vehicle-2',
    notes: [],
    schedule: [],
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'driver-3',
    firstName: 'Pierre',
    lastName: 'Lefevre',
    email: 'pierre.lefevre@example.com',
    phone: '+33655555555',
    address: '789 Rue de Rivoli, 75001 Paris',
    licenseNumber: '5555555555',
    availability: 'Available',
    vehicleId: 'vehicle-3',
    notes: [],
    schedule: [],
    rating: 4.2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'driver-4',
    firstName: 'Sophie',
    lastName: 'Garcia',
    email: 'sophie.garcia@example.com',
    phone: '+33611111111',
    address: '10 Avenue Montaigne, 75008 Paris',
    licenseNumber: '1111111111',
    availability: 'On Leave',
    vehicleId: 'vehicle-4',
    notes: [],
    schedule: [],
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'driver-5',
    firstName: 'Lucas',
    lastName: 'Moreau',
    email: 'lucas.moreau@example.com',
    phone: '+33622222222',
    address: '22 Rue du Faubourg Saint-Honoré, 75008 Paris',
    licenseNumber: '2222222222',
    availability: 'Available',
    vehicleId: 'vehicle-5',
    notes: [],
    schedule: [],
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockVehicles: TransportVehicle[] = [
  {
    id: 'vehicle-1',
    name: 'Mercedes Sprinter',
    type: 'Van',
    model: 'Sprinter',
    make: 'Mercedes-Benz',
    year: 2018,
    licensePlate: 'AB-123-CD',
    capacity: 8,
    availability: 'Available',
    location: 'Paris',
    notes: [],
    maintenanceSchedule: [],
    incidentRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vehicle-2',
    name: 'BMW X5',
    type: 'SUV',
    model: 'X5',
    make: 'BMW',
    year: 2020,
    licensePlate: 'EF-456-GH',
    capacity: 5,
    availability: 'In Maintenance',
    location: 'Lyon',
    notes: [],
    maintenanceSchedule: [],
    incidentRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vehicle-3',
    name: 'Renault Clio',
    type: 'Sedan',
    model: 'Clio',
    make: 'Renault',
    year: 2019,
    licensePlate: 'IJ-789-KL',
    capacity: 5,
    availability: 'Available',
    location: 'Marseille',
    notes: [],
    maintenanceSchedule: [],
    incidentRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vehicle-4',
    name: 'Peugeot 308',
    type: 'Hatchback',
    model: '308',
    make: 'Peugeot',
    year: 2021,
    licensePlate: 'MN-012-OP',
    capacity: 5,
    availability: 'Available',
    location: 'Toulouse',
    notes: [],
    maintenanceSchedule: [],
    incidentRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vehicle-5',
    name: 'Citroen C4',
    type: 'Hatchback',
    model: 'C4',
    make: 'Citroen',
    year: 2022,
    licensePlate: 'QR-345-ST',
    capacity: 5,
    availability: 'Available',
    location: 'Bordeaux',
    notes: [],
    maintenanceSchedule: [],
    incidentRecords: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockVehicleLocations: TransportVehicleLocation[] = [
  {
    vehicleId: 'vehicle-1',
    latitude: 48.8566,
    longitude: 2.3522,
    timestamp: new Date().toISOString(),
  },
  {
    vehicleId: 'vehicle-2',
    latitude: 45.7640,
    longitude: 4.8357,
    timestamp: new Date().toISOString(),
  },
  {
    vehicleId: 'vehicle-3',
    latitude: 43.2965,
    longitude: 5.3698,
    timestamp: new Date().toISOString(),
  },
  {
    vehicleId: 'vehicle-4',
    latitude: 43.6043,
    longitude: 1.4429,
    timestamp: new Date().toISOString(),
  },
  {
    vehicleId: 'vehicle-5',
    latitude: 44.8378,
    longitude: -0.5792,
    timestamp: new Date().toISOString(),
  },
];

export const driverSchedules = [
  {
    driverId: 'driver-1',
    startTime: '08:00',
    endTime: '17:00',
    date: '2023-08-15',
  },
  {
    driverId: 'driver-2',
    startTime: '09:00',
    endTime: '18:00',
    date: '2023-08-15',
  },
  {
    driverId: 'driver-3',
    startTime: '10:00',
    endTime: '19:00',
    date: '2023-08-15',
  },
];

export const driverAvailability: DriverAvailabilityPeriod[] = [
  {
    driverId: 'driver-1',
    startTime: '08:00',
    endTime: '17:00',
    startDate: '2023-08-15',
    endDate: '2023-08-20',
  },
  {
    driverId: 'driver-2',
    startTime: '09:00',
    endTime: '18:00',
    startDate: '2023-08-15',
    endDate: '2023-08-20',
  },
  {
    driverId: 'driver-3',
    startTime: '10:00',
    endTime: '19:00',
    startDate: '2023-08-15',
    endDate: '2023-08-20',
  },
];

export const extensionRequests: MapExtensionRequest[] = [
  {
    id: "ext-1",
    extended: true,
    fullscreen: false,
    status: "pending" as const,
    clientName: "Entreprise ABC",
    vehicleName: "Mercedes Sprinter",
    driverName: "Jean Dupont",
    reason: "Client needs the vehicle for another two hours",
    originalEndTime: "16:00",
    newEndTime: "18:00",
    originalEndDate: "2023-08-15",
    requestedEndDate: "2023-08-15",
    extensionReason: "Meeting running longer than expected",
    requestId: "req-001"
  },
  {
    id: "ext-2",
    extended: false,
    fullscreen: true,
    status: "approved" as const,
    clientName: "Société XYZ",
    vehicleName: "BMW X5",
    driverName: "Marie Martin",
    reason: "Client requested a larger display for presentation",
    originalEndTime: "14:00",
    newEndTime: "14:00",
    originalEndDate: "2023-08-16",
    requestedEndDate: "2023-08-16",
    requestId: "req-002"
  },
];
