import { TransportVehicle, TransportDriver, VehicleMaintenanceSchedule, MapExtensionRequest } from "../types";

// Mock vehicles data
export const vehicles: TransportVehicle[] = [
  {
    id: "veh-001",
    name: "Mercedes S-Class",
    licensePlate: "ABC-123",
    capacity: 4,
    status: "available",
    location: {
      vehicleId: "veh-001",
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      timestamp: new Date().toISOString(),
      status: "idle",
      speed: 0,
      heading: 0,
    },
    driverName: "Thomas Dubois",
    notes: [],
  },
  {
    id: "veh-002",
    name: "BMW 5 Series",
    licensePlate: "XYZ-789",
    capacity: 4,
    status: "available",
    location: {
      vehicleId: "veh-002",
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      timestamp: new Date().toISOString(),
      status: "idle",
      speed: 0,
      heading: 0,
    },
    driverName: "Marie Curie",
    notes: [],
  },
  {
    id: "veh-003",
    name: "Renault Clio",
    licensePlate: "LMN-456",
    capacity: 5,
    status: "available",
    location: {
      vehicleId: "veh-003",
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      timestamp: new Date().toISOString(),
      status: "idle",
      speed: 0,
      heading: 0,
    },
    driverName: "Jean Valjean",
    notes: [],
  },
  {
    id: "veh-004",
    name: "Peugeot 3008",
    licensePlate: "QRS-321",
    capacity: 5,
    status: "available",
    location: {
      vehicleId: "veh-004",
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      timestamp: new Date().toISOString(),
      status: "idle",
      speed: 0,
      heading: 0,
    },
    driverName: "Victor Hugo",
    notes: [],
  },
];

// Mock maintenance schedules
export const maintenanceSchedules: Partial<VehicleMaintenanceSchedule>[] = [
  {
    id: "maint-001",
    vehicleId: "veh-001",
    type: "regular",
    description: "Changement d'huile et filtres",
    scheduledDate: "2023-12-05",
    estimatedDuration: 120,
    technicianAssigned: "Jean Dupont",
    status: "scheduled",
    startDate: "2023-12-05",
    endDate: "2023-12-05",
    notes: [],
  },
  {
    id: "maint-002",
    vehicleId: "veh-002",
    type: "repair",
    description: "Réparation de la climatisation",
    scheduledDate: "2023-12-10",
    estimatedDuration: 90,
    technicianAssigned: "Alice Martin",
    status: "scheduled",
    startDate: "2023-12-10",
    endDate: "2023-12-10",
    notes: [],
  },
];

// Mock extension requests
export const extensionRequests: Partial<MapExtensionRequest>[] = [
  {
    id: "ext-001",
    requestId: "REQ-001",
    clientName: "Sophie Martin",
    vehicleName: "Mercedes S-Class",
    vehicleId: "veh-001",
    driverId: "drv-001",
    driverName: "Thomas Dubois",
    originalEndDate: "2023-11-15",
    requestedEndDate: "2023-11-18",
    status: "pending",
    reason: "Prolongation du séjour d'affaires",
    createdAt: "2023-11-10",
    type: "extension",
    active: true,
  },
  {
    id: "ext-002",
    requestId: "REQ-002",
    clientName: "Pierre Dupont",
    vehicleName: "BMW 5 Series",
    vehicleId: "veh-002",
    driverId: "drv-002",
    driverName: "Marie Curie",
    originalEndDate: "2023-11-20",
    requestedEndDate: "2023-11-25",
    status: "approved",
    reason: "Changement de plan",
    createdAt: "2023-11-15",
    type: "extension",
    active: false,
  },
];

// Mock drivers data
export const drivers: TransportDriver[] = [
  {
    id: "drv-001",
    firstName: "Thomas",
    lastName: "Dubois",
    phone: "0123456789",
    email: "thomas.dubois@example.com",
    licenseNumber: "D123456",
    licenseExpiry: "2025-12-31",
    available: true,
    onLeave: false,
    rating: 4.5,
    experience: 5,
    language: ["French", "English"],
    preferredVehicleType: ["sedan"],
    status: "active",
    notes: [],
  },
  {
    id: "drv-002",
    firstName: "Marie",
    lastName: "Curie",
    phone: "0987654321",
    email: "marie.curie@example.com",
    licenseNumber: "D987654",
    licenseExpiry: "2024-11-30",
    available: true,
    onLeave: false,
    rating: 4.8,
    experience: 7,
    language: ["French", "English"],
    preferredVehicleType: ["luxury"],
    status: "active",
    notes: [],
  },
  {
    id: "drv-003",
    firstName: "Jean",
    lastName: "Valjean",
    phone: "1234567890",
    email: "jean.valjean@example.com",
    licenseNumber: "D123789",
    licenseExpiry: "2023-10-15",
    available: false,
    onLeave: true,
    rating: 4.0,
    experience: 3,
    language: ["French"],
    preferredVehicleType: ["van"],
    status: "on_leave",
    notes: [],
  },
];
