
export const FIREBASE_COLLECTIONS = {
  USERS: 'users',
  COMPANIES: 'companies',
  DEPARTMENTS: 'departments',
  EMPLOYEES: 'employees',
  DOCUMENTS: 'documents',
  SETTINGS: 'settings',
  CONTACTS: 'contacts',
  
  CRM: {
    CLIENTS: 'crm/clients',
    PROSPECTS: 'crm/prospects',
    REMINDERS: 'crm/reminders',
    OPPORTUNITIES: 'crm/opportunities',
    LEADS: 'crm/leads',
    CONTACTS: 'crm/contacts',
    DEALS: 'crm/deals',
    SETTINGS: 'crm/settings',
  },
  
  ACCOUNTING: {
    INVOICES: 'accounting/invoices',
    PAYMENTS: 'accounting/payments',
    EXPENSES: 'accounting/expenses',
    CLIENTS: 'accounting/clients',
    SUPPLIERS: 'accounting/suppliers',
    REPORTS: 'accounting/reports',
    TAXES: 'accounting/taxes',
    SETTINGS: 'accounting/settings',
    TRANSACTIONS: 'accounting/transactions',
    PERMISSIONS: 'accounting/permissions',
  },
  
  HR: {
    EMPLOYEES: 'hr-employees',
    LEAVES: 'hr-leaves',
    CONTRACTS: 'hr-contracts',
    POSITIONS: 'hr-positions',
    DEPARTMENTS: 'hr-departments',
    EVALUATIONS: 'hr-evaluations',
    PAYSLIPS: 'hr-payslips',
    RECRUITMENT: 'hr-recruitment',
    TRAININGS: 'hr-trainings',
    BADGES: 'hr-badges',
    ATTENDANCE: 'hr-attendance',
    ABSENCE_REQUESTS: 'hr-absence_requests',
    DOCUMENTS: 'hr-documents',
    TIMESHEETS: 'hr-timesheets',
    REPORTS: 'hr-reports',
    ALERTS: 'hr-alerts',
    LEAVE_REQUESTS: 'hr-leave_requests',
    ABSENCES: 'hr-absences',
    SALARIES: 'hr-salaries',
  },
  
  HEALTH: {
    PATIENTS: 'health-patients',
    DOCTORS: 'health-doctors',
    APPOINTMENTS: 'health-appointments',
    CONSULTATIONS: 'health-consultations',
    MEDICAL_RECORDS: 'health-medical_records',
    PRESCRIPTIONS: 'health-prescriptions',
    INSURANCE: 'health-insurance',
    BILLING: 'health-billing',
    SETTINGS: 'health-settings',
    HEALTH_CONSULTATIONS: 'health-consultations',
    HEALTH_INSURANCE: 'health-insurance',
    HEALTH_BILLING: 'health-billing',
    STAFF: 'health-staff',
  },
  
  USER_PERMISSIONS: 'userPermissions',
};
